### ISSUE TITLE
crash of v0.2.3-2-gae1aa82

### ISSUE THREAD

**Issue by codeck** [stellar/stellar-core#889]
i updated my nodes to ae1aa82 and all was synced. but 3 of them crashed without detail message.

```
2015-10-29T08:02:10.107 GDPJ4 [Herder INFO ] Quorum information for 471407 : {"agree":7,"disagree":0,"fail_at":3,"hash":"bd4db9","missing":0,"phase":"EXTERNALIZE"}
2015-10-29T08:02:10.107 GDPJ4 [Ledger INFO ] Got consensus: [seq=471409, prev=8f77d9, tx_count=0, sv: [  txH: 261d7e, ct: 1446105729, upgrades: [ ] ]]
2015-10-29T08:02:10.115 GDPJ4 [Ledger INFO ] Closed ledger: [seq=471409, hash=108bc5]
2015-10-29T08:02:18.093 GDPJ4 [Herder INFO ] Quorum information for 471408 : {"agree":7,"disagree":0,"fail_at":3,"hash":"bd4db9","missing":0,"phase":"EXTERNALIZE"}
2015-10-29T08:02:18.093 GDPJ4 [Ledger INFO ] Got consensus: [seq=471410, prev=108bc5, tx_count=0, sv: [  txH: 186daf, ct: 1446105734, upgrades: [ ] ]]
2015-10-29T08:02:18.097 GDPJ4 [Ledger INFO ] Closed ledger: [seq=471410, hash=8f248c]
Segmentation fault (core dumped)
# stellar-core --version
v0.2.3-2-gae1aa82
```

**Comment by codeck** [comment]
stack frames
```
#0  TxSetFrame (other=..., this=<optimized out>) at ./herder/TxSetFrame.h:29
#1  construct<stellar::TxSetFrame, stellar::TxSetFrame&> (this=<optimized out>, __p=<optimized out>, __args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/ext/new_allocator.h:120
#2  _S_construct<stellar::TxSetFrame, stellar::TxSetFrame&> (__a=..., __p=<optimized out>, __args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/alloc_traits.h:253
#3  construct<stellar::TxSetFrame, stellar::TxSetFrame&> (__a=..., __p=<optimized out>, __args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/alloc_traits.h:399
#4  _Sp_counted_ptr_inplace<stellar::TxSetFrame&> (this=<optimized out>, __a=..., __args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/shared_ptr_base.h:515
#5  construct<std::_Sp_counted_ptr_inplace<stellar::TxSetFrame, std::allocator<stellar::TxSetFrame>, __gnu_cxx::_Lock_policy::_S_atomic>, std::allocator<stellar::TxSetFrame> const, stellar::TxSetFrame&> (this=<optimized out>, __p=<optimized out>, __args=..., __args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/ext/new_allocator.h:120
#6  _S_construct<std::_Sp_counted_ptr_inplace<stellar::TxSetFrame, std::allocator<stellar::TxSetFrame>, __gnu_cxx::_Lock_policy::_S_atomic>, std::allocator<stellar::TxSetFrame> const, stellar::TxSetFrame&> (__a=..., __p=<optimized out>, __args=..., __args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/alloc_traits.h:253
#7  construct<std::_Sp_counted_ptr_inplace<stellar::TxSetFrame, std::allocator<stellar::TxSetFrame>, __gnu_cxx::_Lock_policy::_S_atomic>, std::allocator<stellar::TxSetFrame> const, stellar::TxSetFrame&> (__a=..., __p=<optimized out>, __args=..., __args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/alloc_traits.h:399
#8  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<stellar::TxSetFrame, std::allocator<stellar::TxSetFrame>, stellar::TxSetFrame&> (this=0x7fff75d92bf8, __a=..., __args=...) at /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/shared_ptr_base.h:619
#9  0x00000000004a7745 in __shared_ptr<std::allocator<stellar::TxSetFrame>, stellar::TxSetFrame&> (__a=..., this=<optimized out>, __tag=...,
    __args=...) at /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/shared_ptr_base.h:1089
#10 shared_ptr<std::allocator<stellar::TxSetFrame>, stellar::TxSetFrame&> (__a=..., this=<optimized out>, __tag=..., __args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/shared_ptr.h:317
#11 allocate_shared<stellar::TxSetFrame, std::allocator<stellar::TxSetFrame>, stellar::TxSetFrame&> (__a=..., __args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/shared_ptr.h:587
#12 make_shared<stellar::TxSetFrame, stellar::TxSetFrame&> (__args=...)
    at /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/bits/shared_ptr.h:603
#13 stellar::HerderImpl::combineCandidates (this=0x1caea50, slotIndex=<optimized out>, candidates=...) at herder/HerderImpl.cpp:790
#14 0x00000000004a82ed in non-virtual thunk to stellar::HerderImpl::combineCandidates(unsigned long, std::set<xdr::xvector<unsigned char, 4294967292u>, std::less<xdr::xvector<unsigned char, 4294967292u> >, std::allocator<xdr::xvector<unsigned char, 4294967292u> > > const&) ()
    at herder/HerderImpl.cpp:687
#15 0x0000000000683d8b in stellar::NominationProtocol::processEnvelope (this=0x2227c58, envelope=...) at scp/NominationProtocol.cpp:409
#16 0x00000000006d5e35 in stellar::Slot::processEnvelope (this=0x2227bc0, envelope=...) at scp/Slot.cpp:114
#17 0x0000000000686d20 in stellar::SCP::receiveEnvelope (this=0x1caea60, envelope=...) at scp/SCP.cpp:40
#18 0x00000000004ababc in stellar::HerderImpl::processSCPQueueUpToIndex (this=<optimized out>, slotIndex=471411) at herder/HerderImpl.cpp:1139
#19 0x00000000004d9eae in stellar::PendingEnvelopes::envelopeReady (this=0x1caeac0, envelope=...) at herder/PendingEnvelopes.cpp:135
#20 0x00000000004d9086 in stellar::PendingEnvelopes::recvSCPEnvelope (this=0x1caeac0, envelope=...) at herder/PendingEnvelopes.cpp:110
```
